#!/usr/bin/env python3
"""
Main entry point file to parse arguments and launch DrGPU.
"""

import argparse
from pathlib import Path

from drgpu.drgpu_launch import launch, load_report, load_config


def main():
    """
    Main function to parse the arguments and launch the program.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('-i', '--report-path', metavar='PATH',
                        help='path to the CSV main report generated by Nsight Compute (NCU).',
                        required=True, action='store')
    parser.add_argument('-o', '--output', metavar='FILE_NAME',
                        help='name of the output decision tree file.', required=False,
                        action='store')
    parser.add_argument('-s', '--source', metavar='CSV_FILE_PATH',
                        help='path to the CSV source mapping exported from NCU.',
                        required=False, action='store')
    parser.add_argument('-c', '--memoryconfig', metavar='PATH',
                        help='absolute path to the memory config or a file name in mem_config',
                        required=False, action='store')
    parser.add_argument('-id', '--id', metavar='ID',
                        help='ID of the kernel you want to analyze.', required=False,
                        dest='kernel_id', action='store')
    args = parser.parse_args()

    report = load_report(Path(args.report_path),
                         Path(args.source) if args.source else None,
                         int(args.kernel_id) if args.kernel_id else None)
    config = load_config(args.memoryconfig)
    launch(report, config, output=args.output)


if __name__ == "__main__":
    main()
